/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ToolName = IDL.Text;
export const Tool = IDL.Record({ 'name' : ToolName, 'price' : IDL.Nat });
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'email' : IDL.Text,
});
export const UsageId = IDL.Nat;
export const Time = IDL.Int;
export const UsageEntry = IDL.Record({
  'usageId' : UsageId,
  'email' : IDL.Text,
  'creditsSpent' : IDL.Nat,
  'timestamp' : Time,
  'toolName' : IDL.Text,
});
export const FeedbackEntry = IDL.Record({
  'feedbackId' : IDL.Nat,
  'email' : IDL.Text,
  'rating' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAvailableTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCredits' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'getToolUsageHistory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(UsageEntry)], []),
  'grantCredits' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'useTool' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'adminSetCredits' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'adminAddCredits' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getLastDailyCreditTime' : IDL.Func([], [IDL.Int], ['query']),
  'submitFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'getFeedbacks' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(FeedbackEntry)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ToolName = IDL.Text;
  const Tool = IDL.Record({ 'name' : ToolName, 'price' : IDL.Nat });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'email' : IDL.Text });
  const UsageId = IDL.Nat;
  const Time = IDL.Int;
  const UsageEntry = IDL.Record({
    'usageId' : UsageId,
    'email' : IDL.Text,
    'creditsSpent' : IDL.Nat,
    'timestamp' : Time,
    'toolName' : IDL.Text,
  });
  const FeedbackEntry = IDL.Record({
    'feedbackId' : IDL.Nat,
    'email' : IDL.Text,
    'rating' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : Time,
  });

  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAvailableTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCredits' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'getToolUsageHistory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(UsageEntry)], []),
    'grantCredits' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
    'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'useTool' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'adminSetCredits' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'adminAddCredits' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getLastDailyCreditTime' : IDL.Func([], [IDL.Int], ['query']),
    'submitFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'getFeedbacks' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(FeedbackEntry)], []),
  });
};

export const init = ({ IDL }) => { return []; };
