/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';

export type Time = bigint;
export interface Tool { 'name' : string, 'price' : bigint }
export interface UsageEntry {
  'usageId' : bigint,
  'email' : string,
  'creditsSpent' : bigint,
  'timestamp' : Time,
  'toolName' : string,
}
export interface UserProfile { 'username' : string, 'email' : string }
export interface FeedbackEntry {
  'feedbackId' : bigint,
  'email' : string,
  'rating' : bigint,
  'message' : string,
  'timestamp' : Time,
}
export interface _SERVICE {
  'register' : ActorMethod<[string, string, string], undefined>,
  'login' : ActorMethod<[string, string], UserProfile>,
  'getCredits' : ActorMethod<[string, string], bigint>,
  'useTool' : ActorMethod<[string, string, string], undefined>,
  'getToolUsageHistory' : ActorMethod<[string, string], Array<UsageEntry>>,
  'getAvailableTools' : ActorMethod<[], Array<Tool>>,
  'adminSetCredits' : ActorMethod<[string, bigint], undefined>,
  'getLastDailyCreditTime' : ActorMethod<[], bigint>,
  'submitFeedback' : ActorMethod<[string, string, bigint, string], undefined>,
  'getFeedbacks' : ActorMethod<[string, string], Array<FeedbackEntry>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
