/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
export type Time = bigint;
export type ToolName = string;
export interface UsageEntry {
    usageId: bigint;
    email: string;
    creditsSpent: bigint;
    timestamp: Time;
    toolName: string;
}
export interface FeedbackEntry {
    feedbackId: bigint;
    email: string;
    rating: bigint;
    message: string;
    timestamp: Time;
}
export interface Tool {
    name: ToolName;
    price: bigint;
}
export interface UserProfile {
    username: string;
    email: string;
}
export interface backendInterface {
    _initializeAccessControlWithSecret(secret: string): Promise<void>;
    register(username: string, email: string, passwordHash: string): Promise<void>;
    login(email: string, passwordHash: string): Promise<UserProfile>;
    getCredits(email: string, passwordHash: string): Promise<bigint>;
    useTool(toolName: string, email: string, passwordHash: string): Promise<void>;
    getToolUsageHistory(email: string, passwordHash: string): Promise<Array<UsageEntry>>;
    getAvailableTools(): Promise<Array<Tool>>;
    adminSetCredits(email: string, amount: bigint): Promise<void>;
    getLastDailyCreditTime(): Promise<bigint>;
    submitFeedback(email: string, passwordHash: string, rating: bigint, message: string): Promise<void>;
    getFeedbacks(email: string, passwordHash: string): Promise<Array<FeedbackEntry>>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                return await this.actor._initializeAccessControlWithSecret(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor._initializeAccessControlWithSecret(arg0);
        }
    }
    async register(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                return await this.actor.register(arg0, arg1, arg2);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.register(arg0, arg1, arg2);
        }
    }
    async login(arg0: string, arg1: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                return await this.actor.login(arg0, arg1);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.login(arg0, arg1);
        }
    }
    async getCredits(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                return await this.actor.getCredits(arg0, arg1);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.getCredits(arg0, arg1);
        }
    }
    async useTool(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                return await this.actor.useTool(arg0, arg1, arg2);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.useTool(arg0, arg1, arg2);
        }
    }
    async getToolUsageHistory(arg0: string, arg1: string): Promise<Array<UsageEntry>> {
        if (this.processError) {
            try {
                return await this.actor.getToolUsageHistory(arg0, arg1);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.getToolUsageHistory(arg0, arg1);
        }
    }
    async getAvailableTools(): Promise<Array<Tool>> {
        if (this.processError) {
            try {
                return await this.actor.getAvailableTools();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.getAvailableTools();
        }
    }
    async adminSetCredits(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                return await this.actor.adminSetCredits(arg0, arg1);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.adminSetCredits(arg0, arg1);
        }
    }
    async getLastDailyCreditTime(): Promise<bigint> {
        if (this.processError) {
            try {
                return await (this.actor as any).getLastDailyCreditTime();
            } catch (e) {
                this.processError(e);
                throw new Error('unreachable');
            }
        } else {
            return await (this.actor as any).getLastDailyCreditTime();
        }
    }
    async submitFeedback(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                return await (this.actor as any).submitFeedback(arg0, arg1, arg2, arg3);
            } catch (e) {
                this.processError(e);
                throw new Error('unreachable');
            }
        } else {
            return await (this.actor as any).submitFeedback(arg0, arg1, arg2, arg3);
        }
    }
    async getFeedbacks(arg0: string, arg1: string): Promise<Array<FeedbackEntry>> {
        if (this.processError) {
            try {
                return await (this.actor as any).getFeedbacks(arg0, arg1);
            } catch (e) {
                this.processError(e);
                throw new Error('unreachable');
            }
        } else {
            return await (this.actor as any).getFeedbacks(arg0, arg1);
        }
    }
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
